### ISSUE TITLE
Demo GIF link broken within Visual Studio Marketplace page

### ISSUE THREAD

**Issue by bland328** [dlindhurst/tabspacerselect#1]
Thanks for creating this extension! FYI, I'm seeing this broken Marketplace image link from within VS Code:

<img width="379" alt="Screen Shot 2022-01-31 at 8 33 49 ᴀᴍ" src="https://user-images.githubusercontent.com/8441277/151812798-1f907371-13af-4c44-8a29-06c317ad2015.png">

**Comment by dlindhurst** [comment]
Thank you for the report. This is fixed.

I'm glad you find this extension useful!
